function readPsTemp (){
return {
    
        "exist:result":{
           "@xmlns:exist":"http://exist.sourceforge.net/NS/exist",
           "@exist:hits":"1",
           "@exist:start":"1",
           "@exist:count":"1",
           "@exist:compilation-time":"0",
           "@exist:execution-time":"0",
           "process_specification":{
              "biblioid":{
                 "docnum":null,
                 "#comment":{
     
                 },
                 "docsubnum":"0",
                 "doctype":"template_ps",
                 "group":"process_specification"
              },
              "info":{
                 "date":null,
                 "time":null,
                 "author":null,
                 "languages":{
                    "@sub":"no-lt",
                    "@main":"en"
                 },
                 "ex":null,
                 "#comment":[
                    {
     
                    },
                    {
     
                    },
                    {
     
                    }
                 ],
                 "document_state":"draft",
                 "document_edition":"0",
                 "type":null,
                 "title":null,
                 "subtitle":null,
                 "searchwords":null
              },
              "content":{
                 "paragraph":{
                    "@para_index":"",
                    "@state":"active",
                    "revision":{
                       "@approval_time":"0",
                       "@rev_index":"",
                       "@approver":"",
                       "@state":"draft",
                       "changelog":null,
                       "para":[
                          {
                             "@language":"en",
                             "@author":"",
                             "@translator":"",
                             "heading":null,
                             "text":null
                          },
                          {
                             "@language":"no",
                             "@author":"",
                             "@translator":"",
                             "heading":null,
                             "text":null
                          },
                          {
                             "@language":"lt",
                             "@author":"",
                             "@translator":"",
                             "heading":null,
                             "text":null
                          }
                       ],
                       "gallery":null
                    }
                 }
              }
           }
        }
     }
}