function readParaTemp(){
    return {
        "exist:result":{
           "@xmlns:exist":"http://exist.sourceforge.net/NS/exist",
           "@exist:hits":"1",
           "@exist:start":"1",
           "@exist:count":"1",
           "@exist:compilation-time":"0",
           "@exist:execution-time":"0",
           "content":{
              "paragraph":{
                 "@para_index":"",
                 "@state":"active",
                 "revision":{
                    "@approval_time":"0",
                    "@rev_index":"",
                    "@approver":"",
                    "@state":"draft",
                    "changelog":null,
                    "para":[
                       {
                          "@language":"en",
                          "@author":"",
                          "@translator":"",
                          "heading":null,
                          "text":null
                       },
                       {
                          "@language":"no",
                          "@author":"",
                          "@translator":"",
                          "heading":null,
                          "text":null
                       },
                       {
                          "@language":"lt",
                          "@author":"",
                          "@translator":"",
                          "heading":null,
                          "text":null
                       }
                    ],
                    "gallery":null
                 }
              }
           }
        }
     };
    
}